//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAccountInfoTbl
    {
        public int MamberAccountId { get; set; }
        public int MemberInfoId { get; set; }
        public double AccountForMill { get; set; }
        public Nullable<double> AccountForFlat { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime PaymentForMonth { get; set; }
    
        public virtual MemberInfoTbl MemberInfoTbl { get; set; }
    }
}
