//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MillInfoTbl
    {
        public int MillInfoId { get; set; }
        public int MemberInfoId { get; set; }
        public double Morning { get; set; }
        public double Lunch { get; set; }
        public double Dinner { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual MemberInfoTbl MemberInfoTbl { get; set; }
    }
}
