//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReportForMill
    {
        public int PaymentReportId { get; set; }
        public int MemberInfoId { get; set; }
        public int TotalMillInfoId { get; set; }
        public double TotalMillPrice { get; set; }
        public double TotalDue { get; set; }
        public double TotalReturn { get; set; }
        public System.DateTime CalculatingMonth { get; set; }
        public bool DueStatus { get; set; }
        public double PaymentTotal { get; set; }
        public double DueTotal { get; set; }
    
        public virtual MemberInfoTbl MemberInfoTbl { get; set; }
        public virtual TotalMillExpenseInfoTbl TotalMillExpenseInfoTbl { get; set; }
    }
}
