//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalMillExpenseInfoTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TotalMillExpenseInfoTbl()
        {
            this.PaymentReportForMills = new HashSet<PaymentReportForMill>();
        }
    
        public int TotalMillInfoId { get; set; }
        public double TotalMill { get; set; }
        public double TotalExpense { get; set; }
        public string ParMill { get; set; }
        public System.DateTime MillExpenseMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentReportForMill> PaymentReportForMills { get; set; }
    }
}
